### ISSUE TITLE
mouse-events-have-key-events reference link not availbale

### ISSUE THREAD

**Issue by LucaVas** [vue-a11y/eslint-plugin-vuejs-accessibility#863] opened 2023-08-03 17:49 UTC
Hi everyone!

When it comes to the following issue:
```@mouseover, @mouseenter, or @hover must be accompanied by @focusin or @focus for accessibility.eslint[vuejs-accessibility/mouse-events-have-key-events](https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/blob/master/docs/mouse-events-have-key-events.md)```
the reference link mentioned is not available: `https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/blob/main/docs/mouse-events-have-key-events.md`.

`404 - page not found
The main branch of eslint-plugin-vuejs-accessibility does not contain the path docs/mouse-events-have-key-events.md.`

Thank you for looking into this!

**Comment by vhoyer** [comment] 2023-08-08 16:10
sorry, we released a new documentation website, but we didn't release a new version of the library, I will do it now, so once updated, you can update your plugin to have the new links working as intended

**Comment by vhoyer** [comment] 2023-08-08 18:14
It should be now fixed on `2.2.0`

**Closed by vhoyer** 2023-08-08 18:14 UTC
